### ISSUE TITLE
BSOD after install the driver

### ISSUE THREAD

**Issue by nikhosagala** [nefarius/ScpToolkit#166] opened 2016-01-17 12:54 UTC
I got blue screen after finish installing the driver. DRIVER_VERIFIER_IOMANAGER_VIOLATION. (ScpVBus.sys)

**Comment by Jan200101** [comment] 2016-01-20 13:17
only @nefarius can help you there

**Comment by RegnarRF** [comment] 2016-01-21 11:48
+, i have this problem too on Windows 10 x64

**Comment by war1ox** [comment] 2016-01-22 01:45
Yeah my pc locks up every other install. I guess its just normal. Lol

**Comment by mirhl** [comment] 2016-01-23 14:03
Duplicate of #29

**Comment by nikhosagala** [comment] 2016-01-23 14:41
Try this, solved my problem

1. Uninstall the driver
2. Open cmd as admin
3. Type verifier.exe /reset
4. Reboot your PC
5. Reinstall the driver

**Comment by nefarius** [comment] 2016-04-02 13:34
This issue is fixed in the upcoming release.

**Closed** 2016-04-10 18:00 UTC
Labels: bug
