### ISSUE TITLE
Couldn't open device

### ISSUE THREAD

**Issue by mmathys** [nefarius/ScpToolkit#197] opened 2016-02-03 19:11 UTC
For some reason, Scp isn't working for me.
- Normal installation (DS3 only, no Bluetooth, no DS4), Windows 10, all dependencies installed, latest version
- Previously installed MotionInJoy. Is this a problem?

![capture](https://cloud.githubusercontent.com/assets/5797176/12793687/fe185d82-cab1-11e5-82f7-5612732ee76f.PNG)

Thanks for your help.

**Comment by SiTWulf** [comment] 2016-02-03 19:55
Maybe motionjoy are not completely uninstalled, the error tells you about OPEN DEVICE... maybe the device is in use with another application (Motionjoy) ...
Please double-check the uninstallation of MotionJoy ...

**Comment by mmathys** [comment] 2016-02-03 21:23
Ok so here's what I did in order to uninstall MotionInJoy:

- Uninstall by uninstaller
- Device Manager: show hidden devices and uninstall any device with a MotionInJoy (I think I unistalled like 3 or so)
- I did `pnputil.exe -e` and `pnputil.exe -f -d oem#.inf` the corresponding file (for me `oem1.inf`)
- Deleted all registry files with motioninjoy (1)
- rebooted.

Is there any way I forgot something?

Still, same error.

**Comment by mmathys** [comment] 2016-02-04 13:43
UPDATE: Reset the PC and installed the drivers again.

Still, the same error as above.

While installing, I got this error too:

![capture9](https://cloud.githubusercontent.com/assets/5797176/12816615/a5bcdd74-cb4d-11e5-9d1b-6e57dfa9f7a5.PNG)

**Comment by mmathys** [comment] 2016-02-07 17:16
@nefarius Could a format and reinstalling of windows help?

**Comment by nefarius** [comment] 2016-02-14 17:35
@mmathys hold on 'till the next version, there are some huge changes involved.

**Comment by axalon** [comment] 2016-02-14 19:14
@nefarius When do you think the next version will be released?

**Comment by LostEnder** [comment] 2016-02-19 00:33
Just wanted to note that I am also having this specific issue. I also actually reinstalled Win 10 in this process for other reasons, but no dice.

Here's hoping the new version comes soon!

**Comment by syepcy** [comment] 2016-04-21 06:53
having the same issue :(

**Comment by nefarius** [comment] 2016-04-24 17:00
Please post a screenshot of the Universal Serial Bus Devices section in your Windows Device Manager.

**Comment by Mezure** [comment] 2016-05-06 05:34
I have the exact same issue with one of my dualshock 3, but the driver works perfectly fine with my other dualshock 3.

Windows 10 and I also had motioninjoy previously installed.

<img width="1279" alt="cappa" src="https://cloud.githubusercontent.com/assets/10646474/15065164/8175c442-1311-11e6-9523-0c6089f35ef6.png">

**Comment by Maxiim112b** [comment] 2016-05-29 08:37
Hey ! Just saw this post, I was having the same problem and I fixed it ! It worked for me: 
![scp](https://cloud.githubusercontent.com/assets/19632116/15632141/20ea8fe2-2589-11e6-96e3-d12654167926.JPG)

When I first installed I didn't checked my controller in the driver installer. I did it and it worked ! Hope it can help you ;) 

Max.

**Comment by cevinator** [comment] 2016-06-30 11:39
Had the same problem, I hit the little reset button on the back of the DS3 once and it's all fixed now. You should try it out.

**Comment by splurmp** [comment] 2016-07-17 11:10
I'm having the same exact problem as OP. I tried the reset button like cevinator suggested but that didn't work. Never had MotionInJoy installed though so it can't be that. 

I did however, have a previous (perfectly working) version of ScpToolkit installed. Unfortunately I was very annoyed by the updater notification that would pop up all the time. I read that it was fixed in a newer version... so I did everything as instructed in this guide: https://github.com/nefarius/ScpToolkit/releases/tag/v1.7.276.16101-BETA

But upon installation I got that same "Couldn't open device" error OP is getting and my DS3 controller didn't work. I tried a bunch of things but no luck and eventually gave up and decided to go back to the old version since that at least worked... but now that doesn't work either. Great.

So now I have no way of using my controller. I'm guessing something messed up with the CleanWipe utility? I dunno. I wish I had just dealt with that annoying notification rather than break everything permanently.

**Comment by sgtpepper42** [comment] 2016-08-10 17:59
Hey I'm also having this problem. Every time I plug my controller in I get that "Couldn't open device" message and whenever I first start the program or try to install the driver for my PS3 controller I get the "System.Nullreference" error message. 

I also used to have MotionJoy, but as far as I can tell I got rid of it. 

Tried resetting my controller, didn't work. Tried redownloading my PS3 driver, didn't work. I'm at a loss now.. any help would be nice.

**Comment by herberto97** [comment] 2016-08-23 00:26
hey is it advisable to use the latest version of scp...i have a lot of problems with it.It never reads the controller.ON the pic below you'll notice that it requests that i connect my controller..but the controller is already plugged at that very moment.this worked very well at the previous version.i only switched to better the service
![screenshot 55](https://cloud.githubusercontent.com/assets/20934908/17876218/54b631e8-68d0-11e6-9f48-78b73eed1c40.png)

**Comment by Volkanite** [comment] 2016-08-23 01:40
@herberto97. I have the same issue with the latest driver installer. The controller must be present in Device Manager under Human Interface Devices. If not, the installer won't see it, as it only enumerates devices under that node by calling SetupDiEnumDeviceInterfaces(GUID_DEVINTERFACE_HID);

I don't know if this is how previous versions of the Driver Installer did it but i think the current version should be fixed to enumerate ALL USB devices, not just those HID compliant devices.

Anyways the workaround for this issue would be to get your controller back under Human Interface Devices. This can be done by manually uninstalling the current driver in Device Manager.

**Comment by herberto97** [comment] 2016-08-25 11:29
@Volkanite  thanks for the help..but that doesnt seem to work..suppossing u wanted me to uninstall it the ps3 drive under "libusb-win32 devices"...but anytime i do so ,it reinstalls and remains there and doesn't go under HIDs..its either i misunderstood you or it doesnt go here....lemme send you a lil pic of when its uninstalled
![screenshot 59](https://cloud.githubusercontent.com/assets/20934908/17967490/5fa5421a-6abf-11e6-9ef7-6ac7c7ecc0bc.png)
...thanks again

**Comment by Volkanite** [comment] 2016-08-28 01:34
Follow the steps below in order to revert to controller to an HID compliant device.
- Right click device
- Update Driver Software
- Browse my computer for driver software
- Let me pick from a list of device drivers on my computer
- USB Input Device
- Click OK

**Comment by herberto97** [comment] 2016-08-28 17:44
@Volkanite  Thank you for that ....but i think i'll stick to the previous version,given that i can't use my in-built bluetooth with my controller in the latest version....Thanks again tho...hope i get to help you in the future

**Comment by Volkanite** [comment] 2016-08-28 18:12
@herberto97 Okay but did my instructions work to get the controller back under Human Interface Devices? The Bluetooth can be fixed as well. The Driver Installer calls SetupDiEnumDeviceInterfaces(GUID_BTHPORT_DEVICE_INTERFACE); which means the device has to present under Bluetooth Radios in Device Manger when you run the installer. This can again be done by reverting to the default Bluetooth driver.

**Comment by herberto97** [comment] 2016-08-28 18:39
@Volkanite yess it did work...my DS3 controller was recognised after it entered HIDs....Pls
 can you throw more emphasis on conveting the bluetooth driver?

**Comment by Volkanite** [comment] 2016-08-28 18:51
@herberto97 Follow the steps below in order to revert to the default bluetooth driver.
- Right click the bluetooth device
- Update Driver Software
- Browse my computer for driver software
- Let me pick from a list of device drivers on my computer
- Generic Bluetooth Adapter
- Click OK

**Comment by herberto97** [comment] 2016-08-28 21:48
@Volkanite Didnt see any Generic Bluetooth Adapter..but here's what  i saw 
![screenshot 63](https://cloud.githubusercontent.com/assets/20934908/18036996/7f17c0aa-6d71-11e6-97b4-e648becdc17a.png)
there's my bluetooth driver
![screenshot 64](https://cloud.githubusercontent.com/assets/20934908/18036997/7f254b1c-6d71-11e6-8b6b-59c6ddd82beb.png)

**Comment by Volkanite** [comment] 2016-08-28 21:58
That should do it. So the Bluetooth adapter now shows up in ScpToolkit Driver Installer?

**Comment by herberto97** [comment] 2016-08-28 22:12
Unfortunately it doesnt..it doesn't go under HID nor is it recognised by scp

**Comment by Volkanite** [comment] 2016-08-29 03:25
@herberto97  Can you run this small piece of code and tell me what the output is?
https://github.com/Volkanite/bluetoothsearch/releases/download/r1/bluetoothSearch.r1.zip

Run it from command prompt.

**Comment by bizaff** [comment] 2016-09-03 03:32
So back to mmathys's original problem - which is the same as my problem except I've never installed MotionInJoy on this machine.  I've seen other issues talking about code signing and what not.. what's the latest?

**Comment by UORasputin** [comment] 2016-09-11 08:53
I found my DS3 Driver in the Device Manager under a strange category and uninstalled it, removing the driver.
After that I could finally install the current driver using the Driver Installer.
It is now listed correctly under USB Devices.
I'm using Windows 10 and had MotionJoy and the old "latest" version installed (which worked).

I think the category was something like libusbk.

**Comment by bardozan** [comment] 2016-09-14 16:30
If there is anyone having the same problem, I can confirm that resetting the DS3 via pushing the little button at the back side works.
Thank you for sharing it.

**Comment by bizaff** [comment] 2016-09-17 06:46
@bardozan - you're absolutely right - that fixed it for me.  This should probably be in the install instructions.

**Comment by andresitogp** [comment] 2016-09-18 17:06
Hi Guys, so, I installed SCP's windows service, bluetooth driver (making sure I tick the built-in bluetooth adapter for my laptop), and dualshock driver (making sure I tick the PS3 controller). It works then, but when I restart I loose my keyboard and one of my usb hard drives. I'm able to login using the on-screen keyboard, uninstall SCP drivers, and the the keyboard and HDD come back immediately. Am I doing something wrong? I have two usb HDDs, but only one dissapears.

**Comment by meatathon** [comment] 2016-09-21 20:45
The solution from @bardozan worked for me too.  Two of my controllers worked, and the other two did not.  Once I pressed the button on the backs of the two with the problem, all four were installed.

**Comment by fevat4574** [comment] 2016-10-16 03:49
bardozan i reset button idea worked for me. ty so much

**Comment by Deltomane** [comment] 2016-11-30 01:45
Hi guys, same problem here!
As I wrote here https://github.com/nefarius/ScpToolkit/issues/110, I'm using my DS3 fake controller via usb cable.
It works for a few seconds, but as soon as I press a button the contoller seems stuck.
When I open the SCPserver window, it shows the same message "Couldn't open device".
I tried the reset button but nothing changed.

**Comment by Master-Kay** [comment] 2016-12-12 03:19
Ok, so... I´m having the same original discussed problem, that mmathys had, he probably solved it with the new updates, good for him, I recently formatted my PC, after reinstalling all browsers and essentials, I went for the scp, as usual, installed the drivers and all, with my controller connected, and it just doesn't open it, the software recognizes the DS3, but it doesn't open the device, I tried everything possible in my hands, reseting the controller, reinstalling the drivers a hundred times, I even tried to use the original scp, it even worked, but after one day it happens the same thing, it recognizes the device, but it doesn't open. 
I really hope someone could help me, this is very important for me, very much important.

Thanks for now

**Comment by gabrielbarr0s** [comment] 2017-01-10 18:03
Resetting the DS3 by pushing the little button at the back side worked for me.

**Comment by Ctesias** [comment] 2017-02-14 04:03
Just ran in to this issue trying to install my DS3 controller.   My problem was that I had the controller plugged in through a USB hub and not directly attached to my tower.

Moving the plug directly to the tower and choosing no specific device in the dropdown to the right when I installed the drivers cleared it up for me.

As an interesting aside, I was sharing the hub with the PS3 controller and my USB blueooth headset.  Whenever I install the DS3 drivers with the tool, it kills all the functionality on my headset aside from the sound.

**Comment by Bre3zeR** [comment] 2017-03-18 11:49
@gabrielbarr0s @nefarius After searching for 4 and half an hour, watching countless of guide, troubleshoot. THIS is what fixed my issue about the open device issue (controller showing as 00:00:00:00:00) and SCP telling me the error.

Since it cost nothing to reset the controller with the little button being it, i advice anybody having issue doing it.

Thanks you sir, you just made my day that much better.

**Comment by chemitasama** [comment] 2017-05-24 14:42
Hi!
I have the same problem, i think so...

Worked correctly but suddenly stopped doing it. I get error "could not open device ..." and "virtual bus error", I tried to uninstall scp, reinstall, restart, stop services, but I can not find solution.
:(

thx for all. if doesn't work thx for all time i can play with my ds3
![sin titulo](https://cloud.githubusercontent.com/assets/28927185/26409107/e9696ae2-409f-11e7-9c39-1ecf2b7ecdd8.jpg)

**Closed** 2018-01-26 19:15 UTC
