### ISSUE TITLE
New DS4 controller is not supported; Installer doesn't detect it

### ISSUE THREAD

**Issue by DryRoastedLemon** [nefarius/ScpToolkit#558] opened 2016-12-28 15:18 UTC
The new Dualshock 4 controller (from the PS4 Pro) is not supported. If there's any info you want me to provide regarding the controller I'll be glad to help.

**Comment by pantra64** [comment] 2016-12-28 19:40
duplicate of #493

**Comment by DryRoastedLemon** [comment] 2016-12-29 12:47
Huh, a rather old issue then. Let's hope support gets added soon!

**Comment by dsrdakota** [comment] 2016-12-30 03:11
I believe there's a new device id: USB\VID_054C&PID_09CC

**Comment by Genesis-Legion** [comment] 2017-01-17 04:43
Any idea if this is something we can fix manually? or would a fix need to be added and recompiled?

**Comment by fklfkl** [comment] 2017-07-31 13:21
I'd also like to report that a DualShock 4 with the above mentioned ID USB\VID_054C&PID_09CC is not detected by the latest installer.

**Closed** 2018-01-26 19:14 UTC
