### ISSUE TITLE
Spam disable

### ISSUE THREAD

**Issue by n1kolaa** [nefarius/ScpToolkit#198] opened 2016-02-04 19:20 UTC
SPC make a lot spam. Are posibole to disable those report from it??

**Comment by nefarius** [comment] 2016-02-06 11:38
What Spam?

**Comment by Hoshiyuu** [comment] 2016-02-06 12:35
I am guessing he is referring to the tray app notification spam.

**Comment by mirhl** [comment] 2016-02-06 17:50
Duplicate of #154 and

> Delete ScpToolkit Tray Notifications shortcut from %ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by nefarius** [comment] 2016-02-14 17:34
You can either follow @mirh 's suggestion or run the setup and uninstall the `ScpToolkit Tray Notifications` component.

**Closed by nefarius** 2016-02-14 17:34 UTC
