### ISSUE TITLE
Can't use DualShock3 controller while Xbox 360 controller is Player 1

### ISSUE THREAD

**Issue by SakifX9** [nefarius/ScpToolkit#115] opened 2016-01-02 12:45 UTC
What I am trying to do is make the DS3 controller player 2, but it won't let me. If I disconnect my Xbox 360 controller and connect my DS3 controller it lets me use it but sets my Xbox 360 controller to Player 2.

(https://github.com/nefarius/ScpServer/files/76235/ScpToolkit_Log-Package_.akif.X9_1451738336.zip)

NOTE: SKIP OCCUPIED GAME SLOTS IS SELECTED.

**Comment by mirhl** [comment] 2016-01-02 17:26
Are you using latest release(31th december)?
There's a checkbox in Service settings in ScpSetting exactly to avoid cases like this. 

@nefarius Is there any reason this is not enabled by default? Even better: why in the world one should keep that disabled?

**Comment by SakifX9** [comment] 2016-01-03 00:29
yeah I only have the latest release installed on my pc

**Comment by mirhl** [comment] 2016-01-03 00:52
AND
*did you try to check that setting*?

**Comment by SakifX9** [comment] 2016-01-03 02:38
yes I did

**Comment by SakifX9** [comment] 2016-01-03 02:40
it was the first thing I did

**Comment by nefarius** [comment] 2016-01-03 17:21
@mirhl: It's not enabled by default 'cause I was afraid (and got feedback in the meantime too) it might still be buggy - which it sadly is. I'm investigating ;)

**Comment by SakifX9** [comment] 2016-01-12 08:16
When I connect the PS3 controller it tells me it's connected to CP Virtual X360 Bus : #01 but when I check Device Manager it says CP Virtual X360 Bus : #02 I think that is contributing to the problem caused.

**Comment by Schroedingers-Cat** [comment] 2016-03-11 11:51
So while this bug is still there, is there a workaround for those who mix DS4 and XBOX360/One gamepads?

**Comment by mirh** [comment] 2016-03-11 12:46
> is there a workaround for those who mix DS4 and XBOX360/One gamepads

Waiting for the dev to fix

Or just use normal DS4 driver
Assuming we aren't talking about those shitty games that disables DirectInput when something XInput is connected, in which case you'd need x360ce

**Comment by nefarius** [comment] 2016-03-11 18:01
It definitely doesn't work reliably to mix "genuine" physical Xbox 360 controllers **and** DS3/4s due to a confirmed bug in the virtual bus driver. I'm currently testing a fixed build but even if I fix it I can't ship the fix yet 'cause I still don't own a code signing certificate (thanks, COMODO! >_<)

**Comment by nileplumb** [comment] 2016-03-14 13:00
@nefarius looking forward to the fixes nefarius! any way to help on the code signing certificate?

**Comment by nefarius** [comment] 2016-03-14 18:10
@nileplumb just a few minutes ago I dumped the request to COMODO, instead got a cert from Certum within only two days!!! Back on track!

**Comment by nefarius** [comment] 2016-03-14 18:24
It's working! They can finally live in harmony side-by-side:

![20160314_191736 1](https://cloud.githubusercontent.com/assets/286631/13755132/03a9bcaa-ea1a-11e5-8fb5-559d085fb4c5.png)

Note that the genuine Xbox 360 Controllers are occupying slots 1 and 2 while the aftermarket DualShock 3 gets slot 3 assigned. What a great feeling :+1:

**Comment by Schroedingers-Cat** [comment] 2016-03-14 18:26
Now that is awesome! Looking forward for the release including this fix!

**Comment by nefarius** [comment] 2016-03-14 18:30
Now I'm not a narcissist by any means but this makes me a little bit proud :')

![12-03-_2016_23-00-05](https://cloud.githubusercontent.com/assets/286631/13755367/30b5fbb8-ea1b-11e5-8a2f-ea7e2e69c3ec.png)

**Comment by charlesmilette** [comment] 2016-03-14 18:32
Is there going to be any special procedures to migrate from the old driver to this one?

**Comment by nefarius** [comment] 2016-03-14 18:33
@charlesmilette I will make the setup do all the heavy lifting and put any manual actions in the notes of the upcoming release. Next build will have some big improvements but will be user-friendly to upgrade.

**Comment by nileplumb** [comment] 2016-03-14 18:55
@nefarius excellent looks like I stepped into the ds3 game at just the right time (well maybe a couple days early) good luck hope to see a compiled release soon!

Ps will this still work fine for the pressure buttons in pcsx2 eg if I turn on PC I should have no Xbox pads connected (currently it thinks there's one, I assume that's Scp related) if I decide to use my ds3 pad it'll assign to pad 1 and I can play MGS3 or whatever fine and pressurized, then switch over to Mario kart for some 4 player action without issue all treated as xinput controllers?

Unplugging and reassigning pad numbers like 360 pads would?

**Comment by mirh** [comment] 2016-03-14 18:58
Pcsx2 uses the custom XInput.dll which you put inside its folder. 
There's nothing to worry with dolphin then.

**Comment by SakifX9** [comment] 2016-03-23 03:40
about when should we expect the next update to address this issue to come out? I'm pretty excited!

**Comment by charlesmilette** [comment] 2016-03-23 19:51
Will the new version require a root CA certificate?

**Comment by nefarius** [comment] 2016-03-23 19:54
@SakifX9 I have some testing left to do, also have to finish the new instructions in the driver installer... If everything goes according to plan maybe upcoming weekend or the one after that.

@charlesmilette no, this would not be possible since kernel-mode drivers have to be signed with a root CA cross-signed by Microsoft, we're doing this legit ;D

**Comment by charlesmilette** [comment] 2016-03-23 19:58
@nefarius Which means that there will still be that "libwdi" root certificate?

**Comment by nefarius** [comment] 2016-03-23 20:05
@charlesmilette the libwdi root certificates are created for the **user-mode** `WinUSB.sys` driver; its auto-generated on every machine so no one (not even myself) can accidentally leak any private keys that could be used to harm other users machines. It's not a mechanism I invented; it's how [libwdi](https://github.com/pbatard/libwdi/wiki) is designed. I'll think about improving this further.

**Comment by SakifX9** [comment] 2016-04-08 06:03
How's the progress going?

**Comment by mirh** [comment] 2016-04-08 16:40
Just wait for newer release, coming soon™

**Comment by nefarius** [comment] 2016-04-10 18:00
@SakifX9 @mirh [Done!](../releases/tag/v1.7.276.16101-BETA)

**Closed** 2016-04-10 18:00 UTC
Labels: bug

**Comment by mirh** [comment] 2016-04-10 19:24
![](https://cloud.githubusercontent.com/assets/9366725/14412408/714b0a72-ff62-11e5-99de-9faec5eb2b2c.PNG)
I hate you

**Comment by nefarius** [comment] 2016-04-10 19:43
@mirh now why's that?

**Comment by charlesmilette** [comment] 2016-04-10 19:44
That's a lot of emails in a short amount of time:
![capture](https://cloud.githubusercontent.com/assets/6440374/14412547/ed53cc2e-ff32-11e5-9851-8bbe4cecc2bf.PNG)

**Comment by nefarius** [comment] 2016-04-10 19:45
@charlesmilette Oops, I guess :3

**Comment by mirh** [comment] 2016-04-10 19:48
Btw, I'm afraid "Every issue linked in this milestone" link points to wrong page (only open issues are showed, but those are closed)

**Comment by nefarius** [comment] 2016-04-10 19:51
@mirh gawddamit. Well, would've been too easy wouldn't it. Correct this another day.

**Comment by candycinema** [comment] 2016-04-20 14:42
@nefarius , this is an awesome build. The setup is very user-friendly. I'm trying to connect a wide variety of controllers at once to my PC, and it's been a long, frustrating quest with one problem after another. I use an XB1 controller wirelessly as my main controller, but having friends over, I use 2 DS3s and probably a DS4 and an Xbox 360 controller. As you can guess, it's tough to get all that working.

This version of SCPToolkit was an easy install and it helps with connecting and disconnecting virtual Xbox360 controllers to rearrange player order. However, I think the clean wipe utility deleted the SCPToolkit Bluetooth Pairing Utility and didn't replace it. In the "official" version of SCP, my controllers connected to the dongle super easily. Now, only the DS4 will, and it still won't work through this new SCPTookit.

1) Is this build focused on getting things to work without the bluetooth pair utility? I noticed that it is deselected in the features install. Is there a reason for that? Is it just too risky to try, or is it known to not function with this build? In the new SCPToolkit Driver Installer, my bluetooth dongle does not appear.
2) How can I roll back to the previous SCP I was using to troubleshoot between this build and the official download? Or maybe re-install this toolkit with the Bluetooth pairing checked off? It's worth noting that I don't have a dongle from the list of known successful dongles.
3) Is this build meant to ignore SCPMonitor? That application can only set DS3/4 controllers to player slots above them, but since it doesn't include attached Xbox controllers, it doesn't seem to be a good tool for anyone who uses both kinds.

**Comment by mirh** [comment] 2016-04-20 15:32
BT pairing is done by SCP service iirc. Pairing utility wasn't needed in the first place. 
This driver should work with both DS, so I see no reason for this problem to happen. I'd suggest to check device manager for right-wrong drivers. 
You can find previous versions [here](https://github.com/nefarius/ScpToolkit/releases). 

Last, I really can't understand what's the fuss with slot order *between* SCP devices (#45 #207) but given the problems in there are supposed to be fixed, if you want to change slot number (especially in a mixed environment) you should be using x360ce.

**Comment by candycinema** [comment] 2016-04-20 18:24
I've ensured that my bluetooth dongle has the right driver. I know pairing is supposed to be done in SCP Driver Installer, and it used to (like magic) with the legacy build, which is why I wanted to troubleshoot it. Is this failure of the bluetooth pairing worth reporting as a new bug/issue? I don't want to fill an old thread with new problems.

**Comment by mirh** [comment] 2016-04-20 18:34
> pairing is supposed to be done in SCP Driver Installer

No, pairing is not done at install time. It's handled by DS3/SCP service (idk right name now). 
Service as in "Windows service". You can see it in task manager too.
